//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUNLUK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLOGEntities1 : DbContext
    {
        public BLOGEntities1()
            : base("name=BLOGEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KATEGORI> KATEGORIs { get; set; }
        public virtual DbSet<KULLANICI> KULLANICIs { get; set; }
        public virtual DbSet<SAYFA> SAYFAs { get; set; }
        public virtual DbSet<YAZI> YAZIs { get; set; }
        public virtual DbSet<YORUM> YORUMs { get; set; }
        public virtual DbSet<VW_YAZI> VW_YAZI { get; set; }
        public virtual DbSet<VW_YAZI_YORUM> VW_YAZI_YORUM { get; set; }
    }
}
